[package]
name = "zeta"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
getrandom = { version = "0.2", features = ["js"] }
yew = { version = "0.20.0", features = ["csr"] }
web-sys = { version = "0.3", featuers = ["HtmlInputElement"] }
gloo-timers = "0.2.6"

